### ISSUE TITLE
Are HerokuConnectModel model classes supposed to create database tables?

### ISSUE THREAD

**Issue by jeanmw** [thermondo/django-heroku-connect#119]
I'm new to heroku connect with Django, although I've used heroku connect with other stacks.
Are migrations from models that inherit from `hc_models.HerokuConnectModel` supposed to create database tables?

I have a django project set up like so (abbreviated for readability)
```
├── app
│   ├── __init__.py
│   ├── common
│   │   ├── __init__.py
│   │   ├── apps.py
│   │   ├── favicon_urls.py
│   │   ├── migrations
│   │   │   └── __init__.py
│   │   ├── models.py
│   │   ├── urls.py
│   │   └── views.py
│   ├── core
│   │   ├── __init__.py
│   │   ├── admin.py
│   │   ├── factories.py
│   │   ├── forms.py
│   │   ├── management
│   │   │   ├── __init__.py
│   │   │   └── commands
│   │   │       ├── __init__.py
│   │   │       └── create_test_data.py
│   │   ├── migrations
│   │   │   ├── 0001_initial.py
│   │   │   └── __init__.py
│   │   ├── models.py
.......
│   ├── urls.py
│   └── wsgi.py
├── manage.py
├── requirements.txt
├── runserver.sh
├── salesforce_company
│   ├── __init__.py
│   ├── admin.py
│   ├── apps.py
│   ├── migrations
│   │   ├── 0001_initial.py
│   │   └── __init__.py
│   ├── models.py
│   ├── tests.py
│   └── views.py
```

I have all mappings set up with heroku connect on the heroku web GUI. I have the database engine set as specified. I have a heroku connect model like so:

```
from django.db import models
from heroku_connect.db import models as hc_models

class SalesforceCompany(hc_models.HerokuConnectModel):
  sf_object_name = 'Account'
  name = hc_models.Text(sf_field_name='Name', max_length=120)
```

And a migration from this model:
```
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesforceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sf_id', heroku_connect.db.models.fields.ID(db_column='sfid', db_index=True, editable=False, max_length=18, null=True, sf_field_name='Id', unique=True, upsert=False)),
                ('system_mod_stamp', heroku_connect.db.models.fields.DateTime(db_column='systemmodstamp', db_index=True, null=True, sf_field_name='SystemModstamp', upsert=False)),
                ('is_deleted', heroku_connect.db.models.fields.Checkbox(db_column='isdeleted', null=True, sf_field_name='IsDeleted', upsert=False)),
                ('_hc_lastop', models.CharField(editable=False, help_text='Indicates the last sync operation Heroku Connect performed on the record', max_length=32, null=True)),
                ('_hc_err', models.TextField(editable=False, help_text='If the last sync operation by Heroku Connect resulted in an error then this column will contain a JSON object containing more information about the error', max_length=1024, null=True)),
                ('name', heroku_connect.db.models.fields.Text(db_column='name', max_length=120, null=True, sf_field_name='Name', upsert=False)),
            ],
            options={
                'db_table': 'salesforce"."account',
                'managed': False,
            },
            bases=(heroku_connect.db.models.base._HerokuConnectSnitchMixin, models.Model),
        ),
    ]
```

The migration runs successfully, but it doesn't look like a table is created. Is that the expected behavior?

When I try to query for model instances in the console, I get an error that the relation does not exist
```
SalesforceCompany.objects.all()
```

And I can also see that no table was created. Forgive me if I am being dense, but is this the intended behavior? If so, how does one interact with the salesforce data from heroku connect? Thanks so much, appreciate your time and work on this project.

**Comment by syphar** [comment]
In our production database, Heroku Connect manages the table creation when you connect the addon, and the mappings are synced. That's why the model definition in the migration file shows `'managed': False,`. 

So after you went through the [deployment steps in the documentation](https://django-heroku-connect.readthedocs.io/en/stable/quick_start.html#deployment), new mappings are generated that match the models you defined. 

For local development you can use the `create_development_schema` command to create the schema locally

**Comment by jeanmw** [comment]
Update: on the deployed instance of my app, I can also see that although the heroku connect addon is configured and there are no errors with any of the linked mappings.
When I query for the tables, they are also missing there:

`heroku pg:psql DATABASE_URL --app {app_name}`

```
```

**Comment by jeanmw** [comment]
I ended up pulling the data with a simple heroku command `heroku pg:pull DATABASE_URL {YOUR LOCAL DB} --app {APP NAME}` for local testing.

**Comment by syphar** [comment]
> I ended up pulling the data with a simple heroku command `heroku pg:pull DATABASE_URL {YOUR LOCAL DB} --app {APP NAME}` for local testing.

@jeanmw I would still be interested in if there is a bug with our library. 

What error did you get with `create_development_schema`? Did you run it with your local database?

**Comment by jeanmw** [comment]
Hi! Thanks for the response.
There was no error when running `create_development_schema` with my local database, there was no error - it simply did not create the tables. Maybe it's something with my database permissions, I'm not sure.
