### ISSUE TITLE
Deprecated django.utils.timezone.utc

### ISSUE THREAD

**Issue by grant0711** [thermondo/django-heroku-connect#121]
https://github.com/django/django/commit/59ab3fd0e9e606d7f0f7ca26609c06ee679ece97

Djano will deprecate django.utils.timezone soon. This is currently being utilized in models/fields.py

Potential fix as follows:

../models/fields.py
```
import datetime

...
class DateTime(HerokuConnectFieldMixin, models.DateTimeField):
    """
    Salesforce ``DateTime`` field.

    Heroku connect create tables with time stamp fields but without time zones, and when it syncs
    to Salesforce it treats them as UTC. This field will be always making sure that the dates are
    aware and UTC.
    """

    def db_type(self, connection):
        return "timestamp without time zone"

    def from_db_value(self, value, *args, **kwargs):
        if value is None:
            return value
        else:
            return value.astimezone(datetime.timezone.utc)
```

**Comment by grant0711** [comment]
![Screenshot from 2023-03-22 14-26-56](https://user-images.githubusercontent.com/47125463/226935571-665056df-6b3f-4a56-9d41-0cf5ca497d24.png)

Current warning in Django==4.1.7 django-heroku-connect==0.25.0

**Comment by syphar** [comment]
just saw, this is a `RemovedInDjango50Warning`, so there is more time :) 

( still happy to take a PR if needed). 

I ran some tests with Django 4.2 RC, and all was fine. 

https://github.com/thermondo/django-heroku-connect/pull/122

**Comment by grant0711** [comment]
Thanks for the quick feedback and turnaround on this.
