### ISSUE TITLE
hc_models.Number.decimal_places attribute not working properly

### ISSUE THREAD

**Issue by Eliagandolfi** [Thermondo/django-heroku-connect#84]
It seems that the hc_models.Number.decimal_places attribute is ineffective.
A few examples:

`numberfield = hc_models.Number(sf_field_name='numberfield__c', decimal_places=x, max_digits=x)`

if numberfield = 18 and
- decimal_places=0, max_digits=1: numberfield = 20
- decimal_places=0, max_digits=2: numberfield = 18
- decimal_places=0, max_digits=3: numberfield = 18.0

if numberfield = 2.6 and
- decimal_places=0, max_digits=1: numberfield = 3
- decimal_places=0, max_digits=2: numberfield = 2.6
- decimal_places=0, max_digits=3: numberfield = 2.60

**Comment by codingjoe** [comment]
Hi @Eliagandolfi,

thanks for reaching out. I see how this might be confusing. W pretend that this is a decimal field, but it really isn't. Sadly Heroku Connect uses double precision float to sync `Number` fields. 

We only have `decimal_places` and `max_digits` to make sure Django forms behaves similar to the Salesforce interface. In SF, you can also specify the digits and decimal places, if I remember correctly and those are enforced by SF if configured.

I hope I could clear things up a little. Let me know if you have any further questions.

Best,
Joe

**Comment by amureki** [comment]
Thank you, Johannes, for the clarifications here!
Exactly as you said, Heroku Connect uses `double` for `Number` fields:
>Number values are stored in Postgres as a double column, which has 15-digit precision. Salesforce values that exceed this limitation will still sync via Heroku Connect, but with reduced precision. This is particularly noticeable with extremely large values.

https://devcenter.heroku.com/articles/heroku-connect-faq#why-does-some-of-my-data-in-postgres-not-match-what-i-wrote-to-salesforce
